version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coinxcel-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://3.85.166.149:8080
      - NODE_ENV=production
    restart: always
    volumes:
      - ./public:/app/public
      # Add a volume for persistent storage if needed
    networks:
      - coinxcel-network

networks:
  coinxcel-network:
    driver: bridge
